import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import AuthProvider from "./providers/AuthProvider";
import DBConnect from "@/services";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
export const metadata = {
  title: "Khana Khazana",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await DBConnect();
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthProvider>
          <Header />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
